import { describe, test, expect } from 'bun:test';
import { getSchemaSQL } from './bundled-schema';
import { BUNDLED_SCHEMA_SQL } from './bundled-schema.generated';

// RED-PHASE SCAFFOLD (EXECUTABLE) — Story 3.1 "Implement Archon Workflow
// Provider Binding Lifecycle"
// (_bmad-output/implementation-artifacts/3-1-implement-archon-workflow-provider-binding-lifecycle.md).
//
// 3.1-CI-001 [P1] — Bundled schema is regenerated and contains table marker.
// Risk: R-007.
//
// This is a genuinely executable red test today: `getSchemaSQL()` in source
// builds reads `migrations/000_combined.sql` straight off disk (no mocking —
// see bundled-schema.ts), and `BUNDLED_SCHEMA_SQL` is the embedded copy for
// binary builds, regenerated by `bun run generate:bundled-schema`. Neither
// currently contains the new table, so both assertions fail today and pass
// once Task 1 adds the table AND `bun run generate:bundled-schema` is run
// (verified separately by `bun run check:bundled-schema`, which this test
// does not replace — it only checks the marker text is present).

describe('provider binding bundled schema marker (Story 3.1)', () => {
  test('getSchemaSQL() (source-build disk read) contains the new table', () => {
    const sql = getSchemaSQL();
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS remote_agent_workflow_provider_bindings');
  });

  test('BUNDLED_SCHEMA_SQL (binary-build embedded copy) contains the new table — regenerate via `bun run generate:bundled-schema`', () => {
    expect(BUNDLED_SCHEMA_SQL).toContain(
      'CREATE TABLE IF NOT EXISTS remote_agent_workflow_provider_bindings'
    );
  });
});

describe('workflow event outbox bundled schema marker (Story 3.5)', () => {
  test('getSchemaSQL() (source-build disk read) contains the outbox tables and private signing secret column', () => {
    const sql = getSchemaSQL();
    expect(sql).toContain("event_types     TEXT NOT NULL DEFAULT '[]'");
    expect(sql).toContain('signing_secret  TEXT');
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS remote_agent_workflow_event_outbox');
    expect(sql).toContain(
      'CREATE TABLE IF NOT EXISTS remote_agent_workflow_event_delivery_attempts'
    );
  });

  test('BUNDLED_SCHEMA_SQL (binary-build embedded copy) contains the outbox tables and private signing secret column', () => {
    expect(BUNDLED_SCHEMA_SQL).toContain("event_types     TEXT NOT NULL DEFAULT '[]'");
    expect(BUNDLED_SCHEMA_SQL).toContain('signing_secret  TEXT');
    expect(BUNDLED_SCHEMA_SQL).toContain(
      'CREATE TABLE IF NOT EXISTS remote_agent_workflow_event_outbox'
    );
    expect(BUNDLED_SCHEMA_SQL).toContain(
      'CREATE TABLE IF NOT EXISTS remote_agent_workflow_event_delivery_attempts'
    );
  });
});
